In [4]:
import pandas as pd
import numpy as np

In [5]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

In [7]:
print(zeros_array,
ones_array, 
constant_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [3 3 3 3 3 3 3 3 3 3]

In [8]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [10]:
array_from_list

array([2, 3, 4])

In [12]:
range_array = np.arange(10)  # Creates an array from 0 to 9
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [27]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)
print(zeros_matrix,
ones_matrix,
constant_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] [[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]

In [30]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column
print(first_row, first_col)

[2 3 4] [2 4]

In [35]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.seed(2)
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))

In [47]:
normal_distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [48]:
random_integers

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

In [72]:
arr1 = np.ones((4,2))
arr2 = np.full((4,2), 3)
result = arr1 + arr2  # Element-wise addition
result = arr1 / arr2  # Element-wise division

In [73]:
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [74]:
arr2

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [75]:
result

array([[0.33333333, 0.33333333],
       [0.33333333, 0.33333333],
       [0.33333333, 0.33333333],
       [0.33333333, 0.33333333]])

In [77]:
pd.__version__

'3.0.3'

In [175]:
import pandas as pd

In [176]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [177]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [178]:
df.fuel_type.nunique()

2

In [179]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [180]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [181]:
df.horsepower.median()

np.float64(149.0)

In [182]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [185]:
h = df.horsepower.fillna(152)

In [188]:
h.median()

np.float64(152.0)

In [207]:
asia_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']][:7]

In [208]:
asia_df

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [213]:
X = asia_df.values

In [214]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [222]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [223]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [224]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [229]:
w = (XTX_inv @ X.T) @ y
w

array([0.01386421, 0.5049067 ])

In [230]:
sum(w)

np.float64(0.5187709081074016)